Assignment 3 

t8220103 Βασίλειος Μυλωνάς

In [2]:
import pandas as pd

In [3]:
choices = pd.read_csv('https://raw.githubusercontent.com/jcpeterson/choices13k/refs/heads/main/c13k_selections.csv')

In [19]:
choices.head()

,Problem,Feedback,n,Block,Ha,pHa,La,Hb,pHb,Lb,LotShapeB,LotNumB,Amb,Corr,bRate,bRate_std
0,1,True,15,2,26,0.95,-1,23,0.05,21,0,1,False,0,0.626667,0.384460
1,2,True,15,4,14,0.60,-18,8,0.25,-5,0,1,True,-1,0.493333,0.413118
2,3,True,17,4,2,0.50,0,1,1.00,1,0,1,False,0,0.611765,0.432843
3,4,True,18,3,37,0.05,8,87,0.25,-31,1,2,False,0,0.222222,0.387383
4,5,False,15,1,26,1.00,26,45,0.75,-36,2,5,False,0,0.586667,0.450185

In [4]:
problems = pd.read_json("https://raw.githubusercontent.com/jcpeterson/choices13k/refs/heads/main/c13k_problems.json", orient='index')

In [27]:
problems

,B,A
0,"[[0.9500000000000001, 21.0], [0.05, 23.0]]","[[0.9500000000000001, 26.0], [0.05, -1.0]]"
1,"[[0.75, -5.0], [0.25, 8.0]]","[[0.6000000000000001, 14.0], [0.4, -18.0]]"
2,"[[1.0, 1.0]]","[[0.5, 2.0], [0.5, 0.0]]"
3,"[[0.75, -31.0], [0.125, 86.5], [0.125, 87.5]]","[[0.05, 37.0], [0.9500000000000001, 8.0]]"
4,"[[0.25, -36.0], [0.375, 41.0], [0.1875, 43.0],...","[[1.0, 26.0], [0.0, 26.0]]"
...,...,...
14563,"[[0.199999999999999, 0.0], [0.8, 42.0]]","[[1.0, 30.0], [0.0, 30.0]]"
14564,"[[0.199999999999999, 7.0], [0.8, 18.0]]","[[0.5, 70.0], [0.5, -42.0]]"
14565,"[[0.6000000000000001, -34.0], [0.0125, 28.5], ...","[[0.4, 8.0], [0.6000000000000001, -17.0]]"
14566,"[[0.5, -12.0], [0.5, 45.0]]","[[0.5, 89.0], [0.5, -49.0]]"
14567,"[[0.5, -4.0], [0.5, 70.0]]","[[0.8, 25.0], [0.199999999999999, 25.0]]"

In [5]:
choices_raw = choices.copy()

In [6]:
problems_raw = problems.copy()

## MODEL 1: LINEAR REGRESSION

After reading the papers, trying to understand where the dataset came from and what features should i use , i understood that this dataset is randomly selected , hence why they are different block numbers for different problems. I am not going to try to exactly analyze what cognitive behaviours are present in the dataset,nor will i try to directly rebuild the BEAST model, but what i will try is feature engineer features that somewhat represent the distinct anomalies with the sensitivity to expected return and the 4 tendecies:pessimism, bias toward equal weighting, sensitivity to payoff sign, and an effort
to minimize the probability of immediate regret

Lets first merge the choices and problems into one dataframe

In [7]:
c13k_w_gambles = choices.join(problems, how="left")

In [31]:
c13k_w_gambles

,Problem,Feedback,n,Block,Ha,pHa,La,Hb,pHb,Lb,LotShapeB,LotNumB,Amb,Corr,bRate,bRate_std,B,A
0,1,True,15,2,26,0.95,-1,23,0.05,21,0,1,False,0,0.626667,0.384460,"[[0.9500000000000001, 21.0], [0.05, 23.0]]","[[0.9500000000000001, 26.0], [0.05, -1.0]]"
1,2,True,15,4,14,0.60,-18,8,0.25,-5,0,1,True,-1,0.493333,0.413118,"[[0.75, -5.0], [0.25, 8.0]]","[[0.6000000000000001, 14.0], [0.4, -18.0]]"
2,3,True,17,4,2,0.50,0,1,1.00,1,0,1,False,0,0.611765,0.432843,"[[1.0, 1.0]]","[[0.5, 2.0], [0.5, 0.0]]"
3,4,True,18,3,37,0.05,8,87,0.25,-31,1,2,False,0,0.222222,0.387383,"[[0.75, -31.0], [0.125, 86.5], [0.125, 87.5]]","[[0.05, 37.0], [0.9500000000000001, 8.0]]"
4,5,False,15,1,26,1.00,26,45,0.75,-36,2,5,False,0,0.586667,0.450185,"[[0.25, -36.0], [0.375, 41.0], [0.1875, 43.0],...","[[1.0, 26.0], [0.0, 26.0]]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14563,13002,True,15,3,30,1.00,30,42,0.80,0,0,1,True,0,0.367619,0.302731,"[[0.199999999999999, 0.0], [0.8, 42.0]]","[[1.0, 30.0], [0.0, 30.0]]"
14564,13003,True,15,5,70,0.50,-42,18,0.80,7,0,1,False,0,0.760000,0.364104,"[[0.199999999999999, 7.0], [0.8, 18.0]]","[[0.5, 70.0], [0.5, -42.0]]"
14565,13004,True,15,5,8,0.40,-17,31,0.40,-34,1,6,False,0,0.666667,0.367747,"[[0.6000000000000001, -34.0], [0.0125, 28.5], ...","[[0.4, 8.0], [0.6000000000000001, -17.0]]"
14566,13005,True,15,2,89,0.50,-49,45,0.50,-12,0,1,False,0,0.386667,0.381476,"[[0.5, -12.0], [0.5, 45.0]]","[[0.5, 89.0], [0.5, -49.0]]"
14567,13006,True,15,3,25,0.80,25,70,0.50,-4,0,1,True,0,0.626667,0.361478,"[[0.5, -4.0], [0.5, 70.0]]","[[0.8, 25.0], [0.199999999999999, 25.0]]"

In [8]:
feature_table = c13k_w_gambles.copy()

feature_table["EV_A"] = feature_table["pHa"] * feature_table["Ha"] + (1 - feature_table["pHa"]) * feature_table["La"]
feature_table["EV_B"] = feature_table["pHb"] * feature_table["Hb"] + (1 - feature_table["pHb"]) * feature_table["Lb"]
feature_table["EV_diff"] = feature_table["EV_B"] - feature_table["EV_A"]

In [9]:
feature_table["Range_A"] = (feature_table["Ha"] - feature_table["La"]).abs()
feature_table["Range_B"] = (feature_table["Hb"] - feature_table["Lb"]).abs()
feature_table["Range_diff"] = feature_table["Range_B"] - feature_table["Range_A"]

In [10]:
feature_table["Worst_A"] = feature_table[["Ha", "La"]].min(axis=1)
feature_table["Worst_B"] = feature_table[["Hb", "Lb"]].min(axis=1)
feature_table["Worst_diff"] = feature_table["Worst_B"] - feature_table["Worst_A"]

In [11]:
feature_table["Amb"] = feature_table["Amb"].astype(int)
feature_table["Feedback"] = feature_table["Feedback"].astype(int)
feature_table["Block"] = feature_table["Block"].astype(int)
feature_table["Corr"] = feature_table["Corr"].astype(int)
feature_table["Feedback_Block"] = feature_table["Feedback"] * feature_table["Block"]

In [12]:
feature_cols = [
    "EV_diff",
    "Range_diff",
    "Worst_diff",
    "Amb",
    # "Feedback",
    # "Block",
    "Feedback_Block",
    "Corr",
]

X = feature_table[feature_cols]
y = feature_table["bRate"]

In [13]:
X

       EV_diff  Range_diff  Worst_diff  Amb  Feedback_Block  Corr
0        -3.55         -25          22    0               2     0
1        -2.95         -19          13    1               4    -1
2         0.00          -2           1    0               4     0
3       -10.95          89         -39    0               3     0
4        -1.25          81         -62    0               0     0
...        ...         ...         ...  ...             ...   ...
14563     3.60          42         -30    1               3     0
14564     1.80        -101          49    0               5     0
14565    -1.00          40         -17    0               5     0
14566    -3.50         -81          37    0               2     0
14567     8.00          74         -29    1               3     0

[14568 rows x 6 columns]

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
scale_cols = ["EV_diff", "Range_diff", "Worst_diff"]

scaler = StandardScaler()
X_scaled = X.copy()
X_scaled[scale_cols] = scaler.fit_transform(X_scaled[scale_cols])

In [16]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_scaled, y)

LinearRegression()

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

In [18]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [19]:
y_pred = lr.predict(X_test)

In [20]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"Linear Regression MAE:  {mae:.4f}")
print(f"Linear Regression RMSE: {rmse:.4f}")
print(f"Linear Regression R²:   {r2:.4f}")

Linear Regression MAE:  0.1337
Linear Regression RMSE: 0.1643
Linear Regression R²:   0.4484

In [21]:
from sklearn.model_selection import cross_val_score

cv_mae = -cross_val_score(
    lr,
    X_scaled,
    y,
    scoring="neg_mean_absolute_error",
    cv=5
)

print(f"CV MAE: mean={cv_mae.mean():.4f}, std={cv_mae.std():.4f}")

CV MAE: mean=0.1332, std=0.0019

In [22]:
coef_table = (
    pd.Series(lr.coef_, index=X.columns)
      .sort_values(key=abs, ascending=False)
)

coef_table

EV_diff           0.125298
Worst_diff        0.069573
Amb               0.047099
Range_diff        0.032113
Corr              0.002382
Feedback_Block    0.002031
dtype: float64

In [23]:
results_linear = {
    "model": "Linear Regression",
    "MAE": mae,
    "RMSE": rmse,
    "R2": r2,
    "CV_MAE_mean": cv_mae.mean(),
    "CV_MAE_std": cv_mae.std()
}

In [24]:
results_linear

{'model': 'Linear Regression',
 'MAE': 0.1336768183408819,
 'RMSE': np.float64(0.16433025633154477),
 'R2': 0.44840794727121114,
 'CV_MAE_mean': np.float64(0.13321764876787778),
 'CV_MAE_std': np.float64(0.0019435749849000292)}

I will stop here since "Human choice behavior contains strong nonlinearities and interactions that linear models cannot capture."

## Random forest with extra features

In [25]:
rf_features = [
    "EV_diff",
    "Range_diff",
    "Worst_diff",
    "EV_A",
    "EV_B",
    "Range_A",
    "Range_B",
    "Worst_A",
    "Worst_B",
    "Amb",
    "Feedback",
    "Block",
    "Feedback_Block",
    "Corr",
    "LotNumB",
    "LotShapeB",
]

X_rf = feature_table[rf_features]
y = feature_table["bRate"]

In [28]:
from sklearn.model_selection import train_test_split

X_train_rf, X_test_rf, y_train, y_test = train_test_split(
    X_rf,
    y,
    test_size=0.2,
    random_state=42
)

In [29]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=300,
    max_depth=None,
    min_samples_leaf=5,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train_rf, y_train)

RandomForestRegressor(min_samples_leaf=5, n_estimators=300, n_jobs=-1,
                      random_state=42)

In [30]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

y_pred_rf = rf.predict(X_test_rf)

mae = mean_absolute_error(y_test, y_pred_rf)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_rf))
r2 = r2_score(y_test, y_pred_rf)

print(f"RF Test MAE:  {mae:.4f}")
print(f"RF Test RMSE: {rmse:.4f}")
print(f"RF Test R²:   {r2:.4f}")

RF Test MAE:  0.0853
RF Test RMSE: 0.1100
RF Test R²:   0.7530

In [31]:
from sklearn.model_selection import cross_val_score

cv_mae_rf = -cross_val_score(
    rf,
    X_rf,
    y,
    scoring="neg_mean_absolute_error",
    cv=5,
    n_jobs=-1
)

print(f"RF CV MAE: mean={cv_mae_rf.mean():.4f}, std={cv_mae_rf.std():.4f}")

RF CV MAE: mean=0.0873, std=0.0014

In [87]:
rf_importance = (
    pd.Series(rf.feature_importances_, index=X_rf.columns)
      .sort_values(ascending=False)
)

rf_importance.head(10)

EV_diff       0.483935
Worst_diff    0.133682
Range_B       0.068319
Worst_B       0.049010
Range_A       0.043872
Worst_A       0.043680
Range_diff    0.041844
EV_A          0.040227
Amb           0.024467
LotNumB       0.021506
dtype: float64

## Hyperparameter tuning

In [88]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

In [94]:
rf = RandomForestRegressor(random_state=42, n_jobs=-1)

param_dist = {
    "n_estimators": [200, 300],
    "max_depth": [None, 10, 20, 30, 40],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 5, 10],
    "max_features": ["sqrt", 0.5, 0.7, 1.0],
    "bootstrap": [True],
}

In [99]:
search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_dist,
    n_iter=40,  # increase to 80
    scoring="neg_mean_absolute_error",
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=2
)

search.fit(X_rf, y)

best_rf = search.best_estimator_
print("Best params:", search.best_params_)
print(f"Best CV MAE: {-search.best_score_:.4f}")

Fitting 5 folds for each of 40 candidates, totalling 200 fits
Best params: {'n_estimators': 200, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 0.5, 'max_depth': 40, 'bootstrap': True}
Best CV MAE: 0.0860

In [100]:
best_rf.fit(X_train_rf, y_train)
y_pred = best_rf.predict(X_test_rf)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"Tuned RF Test MAE:  {mae:.4f}")
print(f"Tuned RF Test RMSE: {rmse:.4f}")
print(f"Tuned RF Test R²:   {r2:.4f}")

Tuned RF Test MAE:  0.0838
Tuned RF Test RMSE: 0.1074
Tuned RF Test R²:   0.7644

## RF regression using XGBOOST

In [32]:
X_xgb = X_rf.copy()
y = feature_table["bRate"].copy()

In [33]:
from xgboost import XGBRegressor

xgb = XGBRegressor(
    n_estimators=400,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror",
    random_state=42,
    n_jobs=4,          
    verbosity=1
)

xgb.fit(X_train_rf, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=400,
             n_jobs=4, num_parallel_tree=None, ...)

In [34]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

y_pred_xgb = xgb.predict(X_test_rf)

mae = mean_absolute_error(y_test, y_pred_xgb)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_xgb))
r2 = r2_score(y_test, y_pred_xgb)

print(f"XGB Test MAE:  {mae:.4f}")
print(f"XGB Test RMSE: {rmse:.4f}")
print(f"XGB Test R²:   {r2:.4f}")

XGB Test MAE:  0.0803
XGB Test RMSE: 0.1025
XGB Test R²:   0.7855

In [40]:
from sklearn.model_selection import cross_val_score

cv_mae_xgb = -cross_val_score(
    xgb,
    X_xgb,
    y,
    scoring="neg_mean_absolute_error",
    cv=5,
    n_jobs=1   # avoid nested parallelism
)

print(f"XGB CV MAE: mean={cv_mae_xgb.mean():.4f}, std={cv_mae_xgb.std():.4f}")

XGB CV MAE: mean=0.0821, std=0.0010

In [75]:
import pandas as pd

xgb_importance = (
    pd.Series(xgb.feature_importances_, index=X_xgb.columns)
      .sort_values(ascending=False)
)

xgb_importance.head(15)

EV_diff       0.262407
Amb           0.083582
Worst_diff    0.081262
Worst_A       0.073309
Range_A       0.067749
Worst_B       0.065830
Range_B       0.061831
EV_A          0.061566
LotNumB       0.052233
LotShapeB     0.050483
Range_diff    0.042927
EV_B          0.040168
Feedback      0.019536
Corr          0.013192
Block         0.012526
dtype: float32

In [76]:
import pandas as pd


booster = xgb.get_booster()

gain = booster.get_score(importance_type="gain")

gain_imp = (pd.Series(gain, name="gain")
            .sort_values(ascending=False)
            .reset_index()
            .rename(columns={"index": "feature"}))

print(gain_imp.head(20))

           feature      gain
0          EV_diff  0.604999
1              Amb  0.192705
2       Worst_diff  0.187354
3          Worst_A  0.169019
4          Range_A  0.156200
5          Worst_B  0.151775
6          Range_B  0.142556
7             EV_A  0.141945
8          LotNumB  0.120428
9        LotShapeB  0.116392
10      Range_diff  0.098971
11            EV_B  0.092611
12        Feedback  0.045042
13            Corr  0.030416
14           Block  0.028880
15  Feedback_Block  0.026279

In [ ]:
from sklearn.inspection import permutation_importance
from sklearn.metrics import mean_absolute_error, make_scorer

mae_scorer = make_scorer(mean_absolute_error, greater_is_better=False)

perm = permutation_importance(
    xgb,
    X_test_rf,
    y_test,
    scoring=mae_scorer,
    n_repeats=20,
    random_state=42,
    n_jobs=-1
)

perm_imp = (
    pd.DataFrame({
        "feature": X_test_rf.columns,
        "mae_increase": -perm.importances_mean,  # flip sign
        "std": perm.importances_std
    })
    .sort_values("mae_increase", ascending=False)
)

perm_imp.head(15)

Changing the feature table

In [115]:
X_changed = X_xgb.copy()

In [116]:
X_changed = X_changed.drop(
    columns=["Feedback", "Block"]
)

In [ ]:
# X_changed = X_changed.drop(
#     columns=["Feedback", "Feedback_Block", "Block", "Corr"]
# )

In [117]:
y = feature_table["bRate"].copy()

In [118]:
from sklearn.model_selection import train_test_split

X_train_rf, X_test_rf, y_train, y_test = train_test_split(
    X_changed,
    y,
    test_size=0.2,
    random_state=42
)

In [149]:
from xgboost import XGBRegressor

xgb_changed = XGBRegressor(
    n_estimators=1000,
    learning_rate=0.03,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    # objective="reg:logistic",
    # objective="reg:squarederror",
    objective="reg:squaredlogerror",
    # objective="reg:absoluteerror",
    # objective="reg:pseudohubererror",
    # objective="binary:logistic",
    # objective="binary:logitraw",
    random_state=42,
    n_jobs=4,          
    verbosity=1
)

xgb_changed.fit(X_train_rf, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.03, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=1000,
             n_jobs=4, num_parallel_tree=None, ...)

In [145]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

y_pred_xgb = xgb_changed.predict(X_test_rf)

## if logit_raw
# y_pred_xgb = 1 / (1 + np.exp(-y_pred_xgb))

mae = mean_absolute_error(y_test, y_pred_xgb)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_xgb))
r2 = r2_score(y_test, y_pred_xgb)

print(f"XGB Test MAE:  {mae:.4f}")
print(f"XGB Test RMSE: {rmse:.4f}")
print(f"XGB Test R²:   {r2:.4f}")

XGB Test MAE:  0.0794
XGB Test RMSE: 0.1012
XGB Test R²:   0.7910

In [95]:
from sklearn.model_selection import cross_val_score

cv_mae_xgb = -cross_val_score(
    xgb_changed,
    X_changed,
    y,
    scoring="neg_mean_absolute_error",
    cv=5,
    n_jobs=1   
)

print(f"XGB CV MAE: mean={cv_mae_xgb.mean():.4f}, std={cv_mae_xgb.std():.4f}")

XGB CV MAE: mean=0.0808, std=0.0011

In [109]:
import pandas as pd

xgb_importance = (
    pd.Series(xgb_changed.feature_importances_, index=X_changed.columns)
      .sort_values(ascending=False)
)

xgb_importance.head(15)

EV_diff           0.246937
Worst_diff        0.123117
Amb               0.084987
Range_A           0.082683
Range_B           0.064735
EV_A              0.060829
Worst_A           0.059266
LotNumB           0.055753
LotShapeB         0.052553
Worst_B           0.051372
Range_diff        0.046518
EV_B              0.042185
Feedback_Block    0.016819
Corr              0.012245
dtype: float32

In [110]:
import pandas as pd


booster = xgb_changed.get_booster()

gain = booster.get_score(importance_type="gain")

gain_imp = (pd.Series(gain, name="gain")
            .sort_values(ascending=False)
            .reset_index()
            .rename(columns={"index": "feature"}))

print(gain_imp.head(20))

           feature      gain
0          EV_diff  0.542133
1       Worst_diff  0.270295
2              Amb  0.186582
3          Range_A  0.181525
4          Range_B  0.142122
5             EV_A  0.133546
6          Worst_A  0.130114
7          LotNumB  0.122402
8        LotShapeB  0.115377
9          Worst_B  0.112784
10      Range_diff  0.102126
11            EV_B  0.092613
12  Feedback_Block  0.036924
13            Corr  0.026883

In [111]:
from sklearn.inspection import permutation_importance
from sklearn.metrics import mean_absolute_error, make_scorer

mae_scorer = make_scorer(mean_absolute_error, greater_is_better=False)

perm = permutation_importance(
    xgb_changed,
    X_test_rf,
    y_test,
    scoring=mae_scorer,
    n_repeats=20,
    random_state=42,
    n_jobs=-1
)

perm_imp = (
    pd.DataFrame({
        "feature": X_test_rf.columns,
        "mae_increase": -perm.importances_mean,  # flip sign
        "std": perm.importances_std
    })
    .sort_values("mae_increase", ascending=False)
)

perm_imp.head(15)

           feature  mae_increase       std
11            Corr      0.000010  0.000038
10  Feedback_Block     -0.001598  0.000171
13       LotShapeB     -0.002431  0.000323
4             EV_B     -0.003036  0.000370
12         LotNumB     -0.005848  0.000311
7          Worst_A     -0.008419  0.000646
9              Amb     -0.009265  0.000459
1       Range_diff     -0.012515  0.000818
5          Range_A     -0.013686  0.000470
3             EV_A     -0.013765  0.000782
8          Worst_B     -0.019840  0.000833
6          Range_B     -0.027130  0.001062
2       Worst_diff     -0.044723  0.001107
0          EV_diff     -0.069615  0.001774

## Hyperparameter tuning with optuna on the XBBOOST model

In [98]:
import optuna
from xgboost import XGBRegressor
from sklearn.model_selection import KFold

In [99]:
cv = KFold(n_splits=5, shuffle=True, random_state=42)

In [146]:
def objective(trial):
    # params = {
    #     "n_estimators": trial.suggest_int("n_estimators", 200, 1200),
    #     "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.2, log=True),
    #     "max_depth": trial.suggest_int("max_depth", 2, 10),
    #     "min_child_weight": trial.suggest_float("min_child_weight", 1e-2, 20.0, log=True),
    #     "subsample": trial.suggest_float("subsample", 0.6, 1.0),
    #     "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
    #     "gamma": trial.suggest_float("gamma", 0.0, 5.0),
    #     "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),
    #     "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10.0, log=True),
    # }
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 800, 2000),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.2),
        "max_depth": trial.suggest_int("max_depth", 4, 8),
        "min_child_weight": trial.suggest_float("min_child_weight", 1e-2, 20.0, log=True),
        "subsample": trial.suggest_float("subsample", 0.8, 0.8),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.8, 0.8),
        # "gamma": trial.suggest_float("gamma", 0.0, 5.0),
        # "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),
        # "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10.0, log=True),
    }
    

    model = XGBRegressor(
        **params,
        objective="reg:squaredlogerror",
        # objective="reg:logistic",
        random_state=42,
        n_jobs=1,         
        verbosity=0
    )

    model.fit(X_train_rf, y_train)
    
    y_pred_xgb = model.predict(X_test_rf)
    mae = mean_absolute_error(y_test, y_pred_xgb)

    # mae = mean_absolute_error(y_test, y_pred_xgb)
    # cross_val_score returns NEGATIVE MAE for this scorer
    # cv_mae = -cross_val_score(
    #     model,
    #     X_rf,
    #     y,
    #     scoring="neg_mean_absolute_error",
    #     cv=cv,
    #     n_jobs=1
    # ).mean()

    return mae

First parameter ranges

In [ ]:
# import numpy as np
# import optuna
# import xgboost as xgb
# from sklearn.model_selection import KFold
# from sklearn.metrics import mean_absolute_error
# from optuna.samplers import TPESampler

# # Fixed CV splitter for reproducibility
# kf = KFold(n_splits=5, shuffle=True, random_state=42)

# # Build DMatrix once (faster)
# X_np = X_changed.values
# y_np = y.values
# dall = xgb.DMatrix(X_np, label=y_np)

# # Precompute folds (list of (train_idx, valid_idx))
# folds = [(tr, va) for tr, va in kf.split(X_np, y_np)]

# def objective(trial):
#     params = {
#         "verbosity": 0,
#         "objective": "reg:squarederror",
#         "eval_metric": "mae",
#         "tree_method": "hist",
#         "seed": 42,

#         # Smarter search space (focused)
#         "max_depth": trial.suggest_int("max_depth", 2, 8),
#         "eta": trial.suggest_float("eta", 0.01, 0.08, log=True),
#         "min_child_weight": trial.suggest_float("min_child_weight", 0.5, 30.0, log=True),
#         "subsample": trial.suggest_float("subsample", 0.6, 1.0),
#         "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
#         "gamma": trial.suggest_float("gamma", 0.0, 5.0),
#         "alpha": trial.suggest_float("alpha", 1e-8, 1.0, log=True),
#         "lambda": trial.suggest_float("lambda", 1e-3, 30.0, log=True),
#     }

#     num_boost_round = trial.suggest_int("num_boost_round", 500, 3000)

#     # Run CV using xgboost.cv (simple + robust)
#     cv_results = xgb.cv(
#         params=params,
#         dtrain=dall,
#         folds=folds,
#         num_boost_round=num_boost_round,
#         early_stopping_rounds=80,
#         verbose_eval=False
#     )

#     # Min of validation MAE over boosting rounds
#     return float(cv_results["test-mae-mean"].min())

Other parameters

In [ ]:
# import numpy as np
# import optuna
# import xgboost as xgb
# from sklearn.model_selection import KFold
# from sklearn.metrics import mean_absolute_error
# from optuna.samplers import TPESampler

# # Fixed CV splitter for reproducibility
# kf = KFold(n_splits=5, shuffle=True, random_state=42)

# # Build DMatrix once (faster)
# X_np = X_rf.values
# y_np = y.values
# dall = xgb.DMatrix(X_np, label=y_np)

# # Precompute folds (list of (train_idx, valid_idx))
# folds = [(tr, va) for tr, va in kf.split(X_np, y_np)]
# def objective_refine(trial):
#     params = {
#         "verbosity": 0,
#         "objective": "reg:squarederror",
#         "eval_metric": "mae",
#         "tree_method": "hist",
#         "seed": 42,

#         # refine around depth=6
#         "max_depth": trial.suggest_int("max_depth", 4, 7),

#         # refine around eta≈0.021
#         "eta": trial.suggest_float("eta", 0.012, 0.035, log=True),

#         # broaden slightly upward to control overfit
#         "min_child_weight": trial.suggest_float("min_child_weight", 0.5, 8.0, log=True),

#         # keep sampling in good region
#         "subsample": trial.suggest_float("subsample", 0.65, 0.95),
#         "colsample_bytree": trial.suggest_float("colsample_bytree", 0.65, 0.95),

#         # allow gamma to matter more (sometimes helps)
#         "gamma": trial.suggest_float("gamma", 0.0, 0.5),

#         # allow meaningful regularization (your best was ~0)
#         "alpha": trial.suggest_float("alpha", 1e-8, 1e-1, log=True),
#         "lambda": trial.suggest_float("lambda", 1e-3, 10.0, log=True),
#     }

#     # keep boosting rounds in the right ballpark, let early stopping decide
#     num_boost_round = trial.suggest_int("num_boost_round", 1200, 3500)

#     cv_results = xgb.cv(
#         params=params,
#         dtrain=dall,
#         folds=folds,
#         num_boost_round=num_boost_round,
#         early_stopping_rounds=80,
#         verbose_eval=False
#     )

#     return float(cv_results["test-mae-mean"].min())

In [147]:
from optuna.samplers import TPESampler

sampler = TPESampler(seed=42)
study = optuna.create_study(direction="minimize", sampler=sampler)

study.optimize(objective, n_trials=100, n_jobs=4, show_progress_bar=True)

print("Best MAE:", study.best_value)
print("Best params:", study.best_params)

[I 2026-02-03 21:53:13,345] A new study created in memory with name: no-name-e3b3d3f2-2eec-4849-b577-a3799cc8050e

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-02-03 21:53:18,442] Trial 3 finished with value: 0.08484859721257783 and parameters: {'n_estimators': 873, 'learning_rate': 0.1471707565351741, 'max_depth': 6, 'min_child_weight': 1.7761645257473837, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 3 with value: 0.08484859721257783.
[I 2026-02-03 21:53:19,269] Trial 0 finished with value: 0.08499672755250039 and parameters: {'n_estimators': 1137, 'learning_rate': 0.1543232891803364, 'max_depth': 6, 'min_child_weight': 15.401146776500143, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 3 with value: 0.08484859721257783.
[I 2026-02-03 21:53:22,412] Trial 2 finished with value: 0.08356384281278896 and parameters: {'n_estimators': 1939, 'learning_rate': 0.11247554366035516, 'max_depth': 5, 'min_child_weight': 12.450611229500637, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 2 with value: 0.08356384281278896.
[I 2026-02-03 21:53:24,748] Trial 1 finished with value: 0.08642949599620936 and parameters: {'n_estimators': 1425, 'learning_rate': 0.15637470141341725, 'max_depth': 7, 'min_child_weight': 0.2716728599444327, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 2 with value: 0.08356384281278896.
[I 2026-02-03 21:53:27,752] Trial 4 finished with value: 0.08567625862184299 and parameters: {'n_estimators': 1472, 'learning_rate': 0.1093839888118245, 'max_depth': 7, 'min_child_weight': 7.817219278684577, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 2 with value: 0.08356384281278896.
[I 2026-02-03 21:53:31,828] Trial 6 finished with value: 0.08209395141206897 and parameters: {'n_estimators': 1596, 'learning_rate': 0.07210675307178838, 'max_depth': 6, 'min_child_weight': 2.0602177590788404, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 6 with value: 0.08209395141206897.
[I 2026-02-03 21:53:33,424] Trial 7 finished with value: 0.084017831371256 and parameters: {'n_estimators': 1883, 'learning_rate': 0.1487417463273368, 'max_depth': 4, 'min_child_weight': 1.7430673528653153, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 6 with value: 0.08209395141206897.
[I 2026-02-03 21:53:34,353] Trial 8 finished with value: 0.08253787698466251 and parameters: {'n_estimators': 1498, 'learning_rate': 0.16477725126174828, 'max_depth': 4, 'min_child_weight': 17.926227424328314, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 6 with value: 0.08209395141206897.
[I 2026-02-03 21:53:35,047] Trial 5 finished with value: 0.08175970773818131 and parameters: {'n_estimators': 1526, 'learning_rate': 0.03578323037886204, 'max_depth': 8, 'min_child_weight': 0.44001521232743745, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 5 with value: 0.08175970773818131.
[I 2026-02-03 21:53:37,399] Trial 9 finished with value: 0.08511014129496339 and parameters: {'n_estimators': 943, 'learning_rate': 0.14120417822335854, 'max_depth': 7, 'min_child_weight': 13.950376522321255, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 5 with value: 0.08175970773818131.
[I 2026-02-03 21:53:39,967] Trial 12 finished with value: 0.08047308724044544 and parameters: {'n_estimators': 1045, 'learning_rate': 0.028040863416850678, 'max_depth': 5, 'min_child_weight': 7.533606740993952, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 12 with value: 0.08047308724044544.
[I 2026-02-03 21:53:44,082] Trial 10 finished with value: 0.07936317228340346 and parameters: {'n_estimators': 1490, 'learning_rate': 0.02003703751465027, 'max_depth': 7, 'min_child_weight': 3.327158237651632, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:53:45,580] Trial 11 finished with value: 0.08402657747652362 and parameters: {'n_estimators': 1650, 'learning_rate': 0.08195074358378814, 'max_depth': 6, 'min_child_weight': 0.07316164959582176, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:53:53,729] Trial 13 finished with value: 0.08019504224384284 and parameters: {'n_estimators': 1210, 'learning_rate': 0.022111333267484545, 'max_depth': 8, 'min_child_weight': 0.025879140974900853, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:53:54,433] Trial 16 finished with value: 0.08186558263621081 and parameters: {'n_estimators': 1186, 'learning_rate': 0.01283825612365519, 'max_depth': 5, 'min_child_weight': 3.8031321312847663, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:53:56,100] Trial 15 finished with value: 0.08014704293651738 and parameters: {'n_estimators': 1187, 'learning_rate': 0.02483253197291696, 'max_depth': 5, 'min_child_weight': 0.035903342057179724, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:54:02,597] Trial 14 finished with value: 0.07967712496846627 and parameters: {'n_estimators': 1172, 'learning_rate': 0.012982978354954808, 'max_depth': 8, 'min_child_weight': 0.034352903064731835, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:54:10,757] Trial 18 finished with value: 0.08672995257249425 and parameters: {'n_estimators': 1241, 'learning_rate': 0.19657510203071643, 'max_depth': 8, 'min_child_weight': 0.010783297684715877, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:54:11,680] Trial 19 finished with value: 0.08209058144288384 and parameters: {'n_estimators': 1308, 'learning_rate': 0.05409864945914188, 'max_depth': 7, 'min_child_weight': 0.07882850662540176, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:54:12,143] Trial 17 finished with value: 0.08248542648886328 and parameters: {'n_estimators': 1238, 'learning_rate': 0.052374917582844835, 'max_depth': 8, 'min_child_weight': 0.015652701179081074, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:54:20,830] Trial 20 finished with value: 0.08270808768549082 and parameters: {'n_estimators': 1290, 'learning_rate': 0.05396019102080852, 'max_depth': 8, 'min_child_weight': 0.12792520728888507, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:54:27,593] Trial 21 finished with value: 0.08199502717266019 and parameters: {'n_estimators': 1748, 'learning_rate': 0.050836307898402724, 'max_depth': 7, 'min_child_weight': 0.15809049989807525, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:54:28,871] Trial 23 finished with value: 0.08468420175173058 and parameters: {'n_estimators': 1753, 'learning_rate': 0.08709823373035326, 'max_depth': 7, 'min_child_weight': 0.7370752110143786, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:54:31,406] Trial 24 finished with value: 0.08007039648799691 and parameters: {'n_estimators': 1062, 'learning_rate': 0.010091012627248016, 'max_depth': 7, 'min_child_weight': 0.03462002535099533, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:54:34,075] Trial 25 finished with value: 0.08217677247552392 and parameters: {'n_estimators': 1070, 'learning_rate': 0.013261270219489321, 'max_depth': 5, 'min_child_weight': 0.02623307014782641, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:54:34,342] Trial 22 finished with value: 0.08334420492561007 and parameters: {'n_estimators': 1715, 'learning_rate': 0.051829113831704944, 'max_depth': 8, 'min_child_weight': 0.21440612313046165, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:54:35,672] Trial 26 finished with value: 0.08308586422194879 and parameters: {'n_estimators': 1063, 'learning_rate': 0.010019484509187196, 'max_depth': 5, 'min_child_weight': 0.037655765483296695, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:54:44,313] Trial 27 finished with value: 0.08047914450274253 and parameters: {'n_estimators': 1369, 'learning_rate': 0.03394351848273057, 'max_depth': 7, 'min_child_weight': 0.031767288520261935, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:54:47,135] Trial 29 finished with value: 0.08013830687772641 and parameters: {'n_estimators': 1379, 'learning_rate': 0.03190385634859383, 'max_depth': 7, 'min_child_weight': 0.05453679586052247, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:54:47,818] Trial 30 finished with value: 0.08086489206865999 and parameters: {'n_estimators': 1378, 'learning_rate': 0.03655516487875827, 'max_depth': 7, 'min_child_weight': 0.9743639907695518, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:54:49,636] Trial 28 finished with value: 0.08102039804800805 and parameters: {'n_estimators': 1362, 'learning_rate': 0.0331304937977689, 'max_depth': 8, 'min_child_weight': 0.7920109174155265, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:54:52,322] Trial 31 finished with value: 0.08036015664136159 and parameters: {'n_estimators': 837, 'learning_rate': 0.03926172141224102, 'max_depth': 7, 'min_child_weight': 0.06667054492904138, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:54:54,130] Trial 32 finished with value: 0.0796942261633457 and parameters: {'n_estimators': 959, 'learning_rate': 0.041826768368250125, 'max_depth': 6, 'min_child_weight': 0.7131725064803097, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:54:54,801] Trial 33 finished with value: 0.08119933215769976 and parameters: {'n_estimators': 954, 'learning_rate': 0.07387352570546254, 'max_depth': 6, 'min_child_weight': 0.44612061566024985, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:54:56,578] Trial 34 finished with value: 0.08148262345319846 and parameters: {'n_estimators': 976, 'learning_rate': 0.06733084768320333, 'max_depth': 6, 'min_child_weight': 0.06462570665542768, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:54:59,199] Trial 35 finished with value: 0.0809539764396407 and parameters: {'n_estimators': 964, 'learning_rate': 0.07041546790155401, 'max_depth': 6, 'min_child_weight': 0.012311323870053995, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:55:01,092] Trial 36 finished with value: 0.0811741869551629 and parameters: {'n_estimators': 959, 'learning_rate': 0.06712276443044368, 'max_depth': 6, 'min_child_weight': 0.40474275827333533, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:55:01,272] Trial 37 finished with value: 0.0794467870415379 and parameters: {'n_estimators': 961, 'learning_rate': 0.021813837096678407, 'max_depth': 6, 'min_child_weight': 4.206435805186634, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:55:04,063] Trial 38 finished with value: 0.07949142272647683 and parameters: {'n_estimators': 1140, 'learning_rate': 0.021089597470697587, 'max_depth': 6, 'min_child_weight': 4.2014171905775175, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:55:06,907] Trial 41 finished with value: 0.08288422472092934 and parameters: {'n_estimators': 863, 'learning_rate': 0.12182117319961921, 'max_depth': 6, 'min_child_weight': 3.152075478975047, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:55:06,909] Trial 39 finished with value: 0.08396800623856926 and parameters: {'n_estimators': 1104, 'learning_rate': 0.1264445041483, 'max_depth': 6, 'min_child_weight': 3.6095028369419238, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 10 with value: 0.07936317228340346.
[I 2026-02-03 21:55:09,676] Trial 40 finished with value: 0.07933049911235103 and parameters: {'n_estimators': 1131, 'learning_rate': 0.019317068272667562, 'max_depth': 7, 'min_child_weight': 3.908539251741436, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 40 with value: 0.07933049911235103.
[I 2026-02-03 21:55:11,392] Trial 42 finished with value: 0.08493573021888912 and parameters: {'n_estimators': 1131, 'learning_rate': 0.12870463880136981, 'max_depth': 6, 'min_child_weight': 4.034399945872882, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 40 with value: 0.07933049911235103.
[I 2026-02-03 21:55:14,266] Trial 43 finished with value: 0.07941565968115621 and parameters: {'n_estimators': 1139, 'learning_rate': 0.01973506794416899, 'max_depth': 6, 'min_child_weight': 6.1903609855862936, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 40 with value: 0.07933049911235103.
[I 2026-02-03 21:55:14,678] Trial 44 finished with value: 0.0795526582385256 and parameters: {'n_estimators': 1135, 'learning_rate': 0.019050300948940755, 'max_depth': 6, 'min_child_weight': 5.003391238908018, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 40 with value: 0.07933049911235103.
[I 2026-02-03 21:55:18,790] Trial 45 finished with value: 0.07923184471458612 and parameters: {'n_estimators': 1445, 'learning_rate': 0.018912666785928962, 'max_depth': 6, 'min_child_weight': 6.7009926040400085, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 45 with value: 0.07923184471458612.
[I 2026-02-03 21:55:20,946] Trial 46 finished with value: 0.07939438651306166 and parameters: {'n_estimators': 1153, 'learning_rate': 0.021039270001045284, 'max_depth': 8, 'min_child_weight': 6.52863961543389, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 45 with value: 0.07923184471458612.
[I 2026-02-03 21:55:22,688] Trial 48 finished with value: 0.08250405747610826 and parameters: {'n_estimators': 1454, 'learning_rate': 0.09791031874031168, 'max_depth': 5, 'min_child_weight': 9.823291362802308, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 45 with value: 0.07923184471458612.
[I 2026-02-03 21:55:23,198] Trial 47 finished with value: 0.079302646248207 and parameters: {'n_estimators': 1454, 'learning_rate': 0.02446388768461169, 'max_depth': 6, 'min_child_weight': 8.571214260940286, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 45 with value: 0.07923184471458612.
[I 2026-02-03 21:55:26,863] Trial 49 finished with value: 0.08164641695060428 and parameters: {'n_estimators': 1458, 'learning_rate': 0.09166064589541256, 'max_depth': 5, 'min_child_weight': 8.18877717369716, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 45 with value: 0.07923184471458612.
[I 2026-02-03 21:55:30,970] Trial 50 finished with value: 0.08078093239797324 and parameters: {'n_estimators': 1449, 'learning_rate': 0.0443268892068355, 'max_depth': 7, 'min_child_weight': 7.9991383431727625, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 45 with value: 0.07923184471458612.
[I 2026-02-03 21:55:35,035] Trial 51 finished with value: 0.08139707559130029 and parameters: {'n_estimators': 1519, 'learning_rate': 0.04571198725002806, 'max_depth': 7, 'min_child_weight': 2.485147695206989, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 45 with value: 0.07923184471458612.
[I 2026-02-03 21:55:35,497] Trial 52 finished with value: 0.08149830920554665 and parameters: {'n_estimators': 1551, 'learning_rate': 0.04491576045434297, 'max_depth': 7, 'min_child_weight': 2.2617991427983415, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 45 with value: 0.07923184471458612.
[I 2026-02-03 21:55:37,446] Trial 53 finished with value: 0.08102954901327662 and parameters: {'n_estimators': 1591, 'learning_rate': 0.045104323991387044, 'max_depth': 7, 'min_child_weight': 19.387461037097566, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 45 with value: 0.07923184471458612.
[I 2026-02-03 21:55:43,061] Trial 55 finished with value: 0.08125128145570117 and parameters: {'n_estimators': 1565, 'learning_rate': 0.02586502033214731, 'max_depth': 4, 'min_child_weight': 19.86367385467539, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 45 with value: 0.07923184471458612.
[I 2026-02-03 21:55:43,411] Trial 54 finished with value: 0.07988188814242186 and parameters: {'n_estimators': 1532, 'learning_rate': 0.027547281304770882, 'max_depth': 7, 'min_child_weight': 2.405834982584055, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 45 with value: 0.07923184471458612.
[I 2026-02-03 21:55:48,633] Trial 57 finished with value: 0.08016835318838116 and parameters: {'n_estimators': 1297, 'learning_rate': 0.027731040492337353, 'max_depth': 8, 'min_child_weight': 5.998801794207817, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 45 with value: 0.07923184471458612.
[I 2026-02-03 21:55:48,956] Trial 56 finished with value: 0.08087035346296147 and parameters: {'n_estimators': 1599, 'learning_rate': 0.028465788515141956, 'max_depth': 8, 'min_child_weight': 6.021094084875288, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 45 with value: 0.07923184471458612.
[I 2026-02-03 21:55:54,030] Trial 59 finished with value: 0.07950605224566092 and parameters: {'n_estimators': 1317, 'learning_rate': 0.017853817962203197, 'max_depth': 8, 'min_child_weight': 11.540952982382835, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 45 with value: 0.07923184471458612.
[I 2026-02-03 21:55:54,548] Trial 58 finished with value: 0.07947143327963078 and parameters: {'n_estimators': 1288, 'learning_rate': 0.01782335361703001, 'max_depth': 8, 'min_child_weight': 6.219969577571129, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 45 with value: 0.07923184471458612.
[I 2026-02-03 21:55:57,021] Trial 61 finished with value: 0.07961559024250123 and parameters: {'n_estimators': 1254, 'learning_rate': 0.01695397857140899, 'max_depth': 6, 'min_child_weight': 12.41764210663805, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 45 with value: 0.07923184471458612.
[I 2026-02-03 21:56:01,716] Trial 60 finished with value: 0.08368298118851576 and parameters: {'n_estimators': 1657, 'learning_rate': 0.060757961287707635, 'max_depth': 8, 'min_child_weight': 12.178887903431116, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 45 with value: 0.07923184471458612.
[I 2026-02-03 21:56:02,799] Trial 62 finished with value: 0.08162647400635364 and parameters: {'n_estimators': 1257, 'learning_rate': 0.06212677857118941, 'max_depth': 6, 'min_child_weight': 1.307445542910525, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 45 with value: 0.07923184471458612.
[I 2026-02-03 21:56:03,255] Trial 63 finished with value: 0.08122844612750872 and parameters: {'n_estimators': 1234, 'learning_rate': 0.05854911998146526, 'max_depth': 6, 'min_child_weight': 1.4645886545398208, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 45 with value: 0.07923184471458612.
[I 2026-02-03 21:56:04,341] Trial 64 finished with value: 0.07973166285808693 and parameters: {'n_estimators': 1003, 'learning_rate': 0.0221582667748675, 'max_depth': 6, 'min_child_weight': 1.3176584780730727, 'subsample': 0.8, 'colsample_bytree': 0.8}. Best is trial 45 with value: 0.07923184471458612.

In [160]:
from sklearn.model_selection import cross_validate
from scipy.stats import sem
best_params = study.best_params

best_xgb = XGBRegressor(
    **best_params,
    objective="reg:squaredlogerror",
    random_state=42,
    n_jobs=4,
    verbosity=0
)


scores = cross_validate(
    best_xgb,
    X_changed,
    y,
    scoring=['r2', 'neg_mean_absolute_error'],
    cv=KFold(n_splits=5, shuffle=True, random_state=42),
    n_jobs=1   
)

best_xgb.fit(X_train_rf, y_train)

y_pred = best_xgb.predict(X_test_rf)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)
# if mae != study.best_value:
#     print("You have made a mistake!!!!")
print(f"Tuned XGB Test MAE:  {study.best_value:.4f}")
print(mae)
print('r2', np.mean(scores['test_r2']), sem(scores['test_r2']))
print('mean_absolute_error',
      np.mean(-scores['test_neg_mean_absolute_error']),
      sem(-scores['test_neg_mean_absolute_error']))
# print(f"Tuned XGB Test Crossvalidated MAE:  {cv_mae_xgb.mean():.4f}, std={cv_mae_xgb.std():.4f}")
print(f"Tuned XGB Test RMSE: {rmse:.4f}")
# print(f"Tuned XGB Test R²:   {r2:.4f}")

Tuned XGB Test MAE:  0.0792
0.07943618614369376
r2 0.7871219223589263 0.002959192195852848
mean_absolute_error 0.08119493356685219 0.0005397538207172701
Tuned XGB Test RMSE: 0.1010

## Lets run a different model, were a complete example is in the lectures, LightGBM

In [154]:
import lightgbm as lgb

lgb_reg = lgb.LGBMRegressor(force_col_wise=True)

In [156]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_changed,
    y,
    test_size=0.2,
    random_state=42
)

In [162]:
lgb_reg.fit(X_train, y_train)
preds = lgb_reg.predict(X_test)

[LightGBM] [Info] Total Bins 1591
[LightGBM] [Info] Number of data points in the train set: 11654, number of used features: 14
[LightGBM] [Info] Start training from score 0.518642

In [ ]:
def objective(trial):

    X_train, X_test, y_train, y_test = train_test_split(
        X_changed,
        y,
        test_size=0.2,
        random_state=42
    )

    dtrain = lgb.Dataset(X_train, label=y_train)
    dvalid = lgb.Dataset(X_test, label=y_test)

    param = {
        "objective": "regression",
        "metric": "mean_squared_error",
        "verbosity": -1,
        "boosting_type": "gbdt",
        "num_leaves": trial.suggest_int("num_leaves", 40, 80),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.1),
        "n_estimators": trial.suggest_int("n_estimators", 500, 1500),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.4, 1.0),
        "subsample": trial.suggest_float("subsample", 0.4, 1.0),
        "subsample_freq": trial.suggest_int("subsample_freq", 0, 10),
        "min_child_samples": trial.suggest_int("min_child_samples", 5, 100),
    }

    # Add a callback for pruning.
    pruning_callback = optuna.integration.LightGBMPruningCallback(
        trial, metric="l2", valid_name="valid")
    gbm = lgb.train(param, dtrain, valid_sets=[dvalid],
                    valid_names="valid",
                    callbacks=[pruning_callback])

    preds = gbm.predict(X_test)
    mae = mean_absolute_error(y_test, preds)
    return mae

In [165]:
SEED = 42

np.random.seed(SEED)

In [232]:
from datetime import datetime
now = datetime.now()
timestamp_string = now.strftime("%Y-%m-%d %H:%M:%S")

study_name = f"lightGBM-bc-{timestamp_string}" # Unique identifier of the study.

study = optuna.create_study(
    study_name=study_name,
    direction="minimize",
    sampler=optuna.samplers.TPESampler(seed=SEED),
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=50),
)
study.optimize(objective, n_trials=100, timeout=600)

print("Best MAE:", study.best_value)
print("Best params:", study.best_params)

[I 2026-02-03 23:21:08,631] A new study created in memory with name: lightGBM-bc-2026-02-03 23:21:08
[I 2026-02-03 23:21:31,951] Trial 0 finished with value: 0.08608057248806052 and parameters: {'num_leaves': 55, 'learning_rate': 0.09556428757689246, 'n_estimators': 1232, 'colsample_bytree': 0.759195090518222, 'subsample': 0.4936111842654619, 'subsample_freq': 1, 'min_child_samples': 10}. Best is trial 0 with value: 0.08608057248806052.
[I 2026-02-03 23:21:36,741] Trial 1 finished with value: 0.08326975417917906 and parameters: {'num_leaves': 75, 'learning_rate': 0.0641003510568888, 'n_estimators': 1208, 'colsample_bytree': 0.41235069657748147, 'subsample': 0.9819459112971965, 'subsample_freq': 9, 'min_child_samples': 25}. Best is trial 1 with value: 0.08326975417917906.
[I 2026-02-03 23:21:40,510] Trial 2 finished with value: 0.08054103937378541 and parameters: {'num_leaves': 47, 'learning_rate': 0.026506405886809047, 'n_estimators': 804, 'colsample_bytree': 0.7148538589793427, 'subsample': 0.6591670111852694, 'subsample_freq': 3, 'min_child_samples': 63}. Best is trial 2 with value: 0.08054103937378541.
[I 2026-02-03 23:21:43,586] Trial 3 finished with value: 0.08074560819505733 and parameters: {'num_leaves': 45, 'learning_rate': 0.03629301836816964, 'n_estimators': 866, 'colsample_bytree': 0.6736419905302216, 'subsample': 0.8711055768358081, 'subsample_freq': 2, 'min_child_samples': 54}. Best is trial 2 with value: 0.08054103937378541.
[I 2026-02-03 23:21:45,748] Trial 4 finished with value: 0.08243115413440724 and parameters: {'num_leaves': 64, 'learning_rate': 0.014180537144799797, 'n_estimators': 1108, 'colsample_bytree': 0.502314474212375, 'subsample': 0.43903095579116774, 'subsample_freq': 10, 'min_child_samples': 97}. Best is trial 2 with value: 0.08054103937378541.
[I 2026-02-03 23:21:48,129] Trial 5 finished with value: 0.08074963014641534 and parameters: {'num_leaves': 73, 'learning_rate': 0.037415239225603365, 'n_estimators': 597, 'colsample_bytree': 0.8105398159072941, 'subsample': 0.6640914962437607, 'subsample_freq': 1, 'min_child_samples': 52}. Best is trial 2 with value: 0.08054103937378541.
[I 2026-02-03 23:21:48,536] Trial 6 pruned. Trial was pruned at iteration 172.
[I 2026-02-03 23:21:49,537] Trial 7 pruned. Trial was pruned at iteration 316.
[I 2026-02-03 23:21:49,690] Trial 8 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:21:50,366] Trial 9 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:21:52,917] Trial 10 pruned. Trial was pruned at iteration 203.
[I 2026-02-03 23:21:58,384] Trial 11 finished with value: 0.08086324487806121 and parameters: {'num_leaves': 48, 'learning_rate': 0.0467892309686795, 'n_estimators': 821, 'colsample_bytree': 0.6660646169403213, 'subsample': 0.7857043430728208, 'subsample_freq': 3, 'min_child_samples': 46}. Best is trial 2 with value: 0.08054103937378541.
[I 2026-02-03 23:21:58,635] Trial 12 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:21:58,868] Trial 13 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:21:59,292] Trial 14 pruned. Trial was pruned at iteration 87.
[I 2026-02-03 23:22:00,965] Trial 15 pruned. Trial was pruned at iteration 355.
[I 2026-02-03 23:22:01,209] Trial 16 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:01,594] Trial 17 pruned. Trial was pruned at iteration 80.
[I 2026-02-03 23:22:01,882] Trial 18 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:03,417] Trial 19 pruned. Trial was pruned at iteration 311.
[I 2026-02-03 23:22:03,599] Trial 20 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:03,862] Trial 21 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:05,653] Trial 22 pruned. Trial was pruned at iteration 368.
[I 2026-02-03 23:22:07,877] Trial 23 finished with value: 0.08131416741022794 and parameters: {'num_leaves': 58, 'learning_rate': 0.053336000366543096, 'n_estimators': 502, 'colsample_bytree': 0.84479438881688, 'subsample': 0.7391484881665329, 'subsample_freq': 1, 'min_child_samples': 51}. Best is trial 2 with value: 0.08054103937378541.
[I 2026-02-03 23:22:08,062] Trial 24 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:08,325] Trial 25 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:08,518] Trial 26 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:09,670] Trial 27 pruned. Trial was pruned at iteration 292.
[I 2026-02-03 23:22:09,830] Trial 28 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:10,046] Trial 29 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:10,312] Trial 30 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:10,527] Trial 31 pruned. Trial was pruned at iteration 59.
[I 2026-02-03 23:22:10,941] Trial 32 pruned. Trial was pruned at iteration 137.
[I 2026-02-03 23:22:14,248] Trial 33 finished with value: 0.08171736478882609 and parameters: {'num_leaves': 49, 'learning_rate': 0.06657595795080025, 'n_estimators': 810, 'colsample_bytree': 0.6439688010277309, 'subsample': 0.9679251695466695, 'subsample_freq': 3, 'min_child_samples': 50}. Best is trial 2 with value: 0.08054103937378541.
[I 2026-02-03 23:22:15,534] Trial 34 pruned. Trial was pruned at iteration 353.
[I 2026-02-03 23:22:15,733] Trial 35 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:16,009] Trial 36 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:16,275] Trial 37 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:16,777] Trial 38 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:16,971] Trial 39 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:17,214] Trial 40 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:19,158] Trial 41 pruned. Trial was pruned at iteration 503.
[I 2026-02-03 23:22:19,634] Trial 42 pruned. Trial was pruned at iteration 142.
[I 2026-02-03 23:22:21,926] Trial 43 finished with value: 0.08104061122102683 and parameters: {'num_leaves': 55, 'learning_rate': 0.05801948443593408, 'n_estimators': 593, 'colsample_bytree': 0.8018644739411696, 'subsample': 0.6661027379566815, 'subsample_freq': 2, 'min_child_samples': 54}. Best is trial 2 with value: 0.08054103937378541.
[I 2026-02-03 23:22:23,556] Trial 44 pruned. Trial was pruned at iteration 324.
[I 2026-02-03 23:22:24,495] Trial 45 pruned. Trial was pruned at iteration 264.
[I 2026-02-03 23:22:25,608] Trial 46 pruned. Trial was pruned at iteration 284.
[I 2026-02-03 23:22:25,780] Trial 47 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:26,105] Trial 48 pruned. Trial was pruned at iteration 113.
[I 2026-02-03 23:22:26,660] Trial 49 pruned. Trial was pruned at iteration 169.
[I 2026-02-03 23:22:26,870] Trial 50 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:28,909] Trial 51 pruned. Trial was pruned at iteration 502.
[I 2026-02-03 23:22:29,180] Trial 52 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:29,703] Trial 53 pruned. Trial was pruned at iteration 157.
[I 2026-02-03 23:22:30,061] Trial 54 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:31,593] Trial 55 pruned. Trial was pruned at iteration 412.
[I 2026-02-03 23:22:32,059] Trial 56 pruned. Trial was pruned at iteration 114.
[I 2026-02-03 23:22:32,229] Trial 57 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:32,658] Trial 58 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:32,985] Trial 59 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:33,183] Trial 60 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:33,552] Trial 61 pruned. Trial was pruned at iteration 98.
[I 2026-02-03 23:22:34,382] Trial 62 pruned. Trial was pruned at iteration 246.
[I 2026-02-03 23:22:37,317] Trial 63 finished with value: 0.08185880494476909 and parameters: {'num_leaves': 47, 'learning_rate': 0.06576898773594295, 'n_estimators': 838, 'colsample_bytree': 0.735059431422076, 'subsample': 0.9249560266579281, 'subsample_freq': 4, 'min_child_samples': 54}. Best is trial 2 with value: 0.08054103937378541.
[I 2026-02-03 23:22:38,906] Trial 64 pruned. Trial was pruned at iteration 339.
[I 2026-02-03 23:22:39,279] Trial 65 pruned. Trial was pruned at iteration 76.
[I 2026-02-03 23:22:39,664] Trial 66 pruned. Trial was pruned at iteration 116.
[I 2026-02-03 23:22:40,091] Trial 67 pruned. Trial was pruned at iteration 76.
[I 2026-02-03 23:22:40,338] Trial 68 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:40,573] Trial 69 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:40,867] Trial 70 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:41,537] Trial 71 pruned. Trial was pruned at iteration 147.
[I 2026-02-03 23:22:41,823] Trial 72 pruned. Trial was pruned at iteration 78.
[I 2026-02-03 23:22:43,426] Trial 73 pruned. Trial was pruned at iteration 407.
[I 2026-02-03 23:22:43,637] Trial 74 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:43,904] Trial 75 pruned. Trial was pruned at iteration 76.
[I 2026-02-03 23:22:44,175] Trial 76 pruned. Trial was pruned at iteration 62.
[I 2026-02-03 23:22:45,005] Trial 77 pruned. Trial was pruned at iteration 213.
[I 2026-02-03 23:22:45,209] Trial 78 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:45,461] Trial 79 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:46,639] Trial 80 pruned. Trial was pruned at iteration 346.
[I 2026-02-03 23:22:46,850] Trial 81 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:47,053] Trial 82 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:47,257] Trial 83 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:47,470] Trial 84 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:47,699] Trial 85 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:47,953] Trial 86 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:48,368] Trial 87 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:48,693] Trial 88 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:48,987] Trial 89 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:49,291] Trial 90 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:49,624] Trial 91 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:49,925] Trial 92 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:50,236] Trial 93 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:50,522] Trial 94 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:51,463] Trial 95 pruned. Trial was pruned at iteration 174.
[I 2026-02-03 23:22:52,315] Trial 96 pruned. Trial was pruned at iteration 143.
[I 2026-02-03 23:22:52,577] Trial 97 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:52,915] Trial 98 pruned. Trial was pruned at iteration 50.
[I 2026-02-03 23:22:53,148] Trial 99 pruned. Trial was pruned at iteration 50.

Best MAE: 0.08054103937378541
Best params: {'num_leaves': 47, 'learning_rate': 0.026506405886809047, 'n_estimators': 804, 'colsample_bytree': 0.7148538589793427, 'subsample': 0.6591670111852694, 'subsample_freq': 3, 'min_child_samples': 63}

In [233]:
print('Number of finished trials: ', len(study.trials))
print('Best trial:')
best_trial = study.best_trial

print('Mae: ', best_trial.value)
print('Params: ', study.best_params)

Number of finished trials:  100
Best trial:
Mae:  0.08054103937378541
Params:  {'num_leaves': 47, 'learning_rate': 0.026506405886809047, 'n_estimators': 804, 'colsample_bytree': 0.7148538589793427, 'subsample': 0.6591670111852694, 'subsample_freq': 3, 'min_child_samples': 63}

In [234]:
gbm = lgb.LGBMRegressor(**best_trial.params)
scores = cross_validate(
    gbm,
    X_changed,
    y,
    scoring=['r2', 'neg_mean_absolute_error'],
    cv=KFold(n_splits=5, shuffle=True, random_state=42),
    n_jobs=1   
)

print('r2', np.mean(scores['test_r2']), sem(scores['test_r2']))
print('MAE',
      np.mean(-scores['test_neg_mean_absolute_error']),
      sem(-scores['test_neg_mean_absolute_error'])
)

r2 0.7852076622236718 0.0028781166374264398
MAE 0.08134902194872598 0.0004380683534706671